
version: "2"
services:
  apostrophe:
    container_name: apostrophe
    restart: always
    build: .
    volumes:
      - ./data/uploads:/app/public/uploads
    environment:
      - APOS_MONGODB_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
